#!/bin/zsh

_DOTFILES_PATH=$(pwd)
_BACKUP_PATH="$HOME/.old_dotfiles"

function _backuo_file {
  [[ -a "$_BACKUP_PATH" ]] || mkdir "$_BACKUP_PATH"
  mv "$1" "$_BACKUP_PATH/$1"
}

function _link_to_home {
  _FILE="$HOME/$1"
  [[ -a "$_FILE" ]] && _backuo_file "$_FILE"
  ln -s "$_DOTFILES_PATH/$1" "$_FILE"
}

function _link_to_config {
  _FILE="$HOME/.config/$1"
  [[ -a "$_FILE" ]] && _backuo_file ".config/$1"
  ln -s "$_DOTFILES_PATH/.config/$1" "$_FILE"
}

# git
_link_to_home .gitignore-glogal
_link_to_home .gitconfig
_link_to_home .czrc

# vim
_link_to_config nvim
_link_to_home .vim
_link_to_home .vimrc

# shell
_link_to_home .aliases
_link_to_home .profile
_link_to_home .bashrc
_link_to_home .bash_profile
_link_to_home .zshrc

# desktop environment
_link_to_config awesome
_link_to_config .compton.conf
_link_to_home .dmrc
_link_to_home .xinitrc
_link_to_home .Xmodmap
_link_to_home .Xresources
_link_to_home .xscreensaver
_link_to_home .gtkrc-2.0
_link_to_home .inputrc
_link_to_home .i3
_link_to_config fontconfig
_link_to_config konsolerc
_link_to_home .cvimrc
_link_to_config cvim
_link_to_config htop
_link_to_config qt5ct
_link_to_config ranger
_link_to_config mimeapps.list
_link_to_config libfm
_link_to_config Thunar
_link_to_config user-dirs.dirs
_link_to_config user-dirs.locale
_link_to_config vlc
_link_to_home .tmux.conf
_link_to_home .ipython

ln -s "$DOTFILES_PATH/.local/share/konsole/nwsome.keytab" "$HOME/.local/share/konsole/nwsome.keytab"
ln -s "$DOTFILES_PATH/.local/share/konsole/nwsome.profile" "$HOME/.local/share/konsole/nwsome.profile"
