#!/bin/zsh

local STS=$(amixer get Master | grep % | awk '{print $NF}' | sed 's/[^(o|n|f)]//g')
local LVL=$(amixer get Master | grep % | awk '{print $4}' | sed 's/[^0-9]//g')
if [ "$LVL" -gt "100" ]; then
    LVL=$(amixer get Master | grep % | awk '{print $6}' | sed 's/[^0-9]//g')
fi

if [ "$STS" = "off" ] ; then
    echo $LVL"M"
else
    echo $LVL"%"
fi
echo $STS
