#!/bin/zsh

local STS=$(amixer get Master | grep -m1 % | awk '{print $NF}' | sed 's/[^(o|n|f)]//g')
local LVL=$(amixer get Master | grep -m1 % | awk '{print $4}' | sed 's/[^0-9]//g')
if [ "$LVL" -gt "101" ] ; then
    local LVL=$(amixer get Master | grep -m1 % | awk '{print $5}' | sed 's/[^0-9]//g')
fi

if [ "$STS" = "off" ] ; then
    echo $LVL"M"
else
    echo $LVL"%"
fi
