# autostart background applications
exec /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# autostarts
exec {
    $xdg-dirs
    $swayidle
    $mako
    $swappy_notify
    $autostart_dex
    $flashfocus
    $wlsunset
    $autotiling
    $foot_server
    $help_menu
    $cliphist_store
    $cliphist_watch
    $mounting_daemon
}

exec_always {
    $kanshi
    $auto_xdg_keyboard
    $poweralert
    [ -x "$(command -v lw)" ] && [ -x "$HOME/.config/sway/scripts/local-wisper.sh" ] && $HOME/.config/sway/scripts/local-wisper.sh preload
    $watch_playerctl
    $calendar_daemon
    $update_rofi_theme
    $create_rofi_config
    $swayr_daemon
    $keyboard_layout_border_reload
    $workspace_icons_reload
}
