### Input configuration
#
# You can get the names of your inputs by running: swaymsg -t get_inputs
# Read `man 5 sway-input` for more information about this section.
#
# input "*" equals all input methods
# to specify settings for a specific input method, use its identifier instead.
# query the connected input methods: `swaymsg -t get_inputs`

input type:keyboard {
    # keyd maps caps-lock to Escape and the physical Escape key to F19
    # query the available layout toggles: `localectl list-x11-keymap-options | grep grp:`
    # query the available led indicators: `localectl list-x11-keymap-options | grep grp_led` enables caps-lock led if not the first layout selected
    xkb_layout us,ru
    xkb_options grp:alt_space_toggle
    repeat_delay 300
    repeat_rate 100
    #xkb_variant ","

}

input type:touchpad {
      dwt enabled
      tap enabled
      natural_scroll enabled
}
